matrix:
  include:
    - language: android
      sudo: required
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - cd android
        - yes | sdkmanager "platforms;android-28"
      before_script:
        - chmod +x gradlew
      script:
        - "./gradlew clean assembleDebug lint jacocoTestReport -PdisablePreDex"
    - language: node_js
      node_js:
        - "iojs"
      before_script:
        - cd gateway-test
        - npm install
      script:
        - npm test