matrix:
  include:
    - language: android
      sudo: required
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_install:
        - cd android
        - yes | sdkmanager "platforms;android-28"
      before_script:
        - chmod +x gradlew
      script:
        - "./gradlew clean assembleDebug lint jacocoTestReport -PdisablePreDex"
      after_script:
        - "java -jar ../codacy-coverage-reporter-4.0.5-assembly.jar report -l Kotlin -r ./loginregistration/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml"
    - language: node_js
      node_js:
        - "iojs"
      before_script:
        - cd gateway-test
        - npm install
      script:
        - npm test
    - language: python
      sudo: required
      dist: xenial
      python:
        - "3.7"
      before_install:
        - cd microservices
      install:
        - sudo pip install -U setuptools
        - sudo pip install -r requirements.txt
      script:
        - sudo pytest
    - language: java
      sudo: required
      jdk: oraclejdk8
      before_cache:
        - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      before_script:
        - chmod +x gradlew
      before_install:
        - cd database
      script:
        - "./gradlew clean build"