version: '2'
volumes:
  dbdata:

services:
  osspmgmt-mysql:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=OSSMGMT
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "33061:3306"
  osspmgmt-spring-boot:
    image: openjdk:8-jdk-alpine
    depends_on:
      - osspmgmt-mysql
    links:
      - osspmgmt-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=OSSMGMT
      - DATABASE_PORT=3306
    volumes:
      - ~/.gradle:/root/.gradle
      - .:/app
    build: .
    command: ./gradlew build
