version: '3'  # version of compose format

services:
  microservices:
    container_name: microservices
    build: # path is relative to docker-compose.yml location
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - './:/usr/src/app'
      - '/usr/src/app'
    ports:
      - 5001:80  # host:container
